apiVersion: v1
kind: Pod
metadata:
  labels:
    app: fastapi
    version: "v1.0"
  name: frontend
spec:
  containers:
  - image: gcr.io/devsecol/python-app:v1
    name: frontend
    ports:
    - containerPort: 80
